version: '3'
services:
  productionPG:
    image: postgres
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: timtran
      POSTGRES_DB: jackrealestate
    ports:
      - '5432:5432'

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '80:8080'
    links:
      - productionPG
